server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态动态创建路由的功能,利用微服务名进行路由
      routes:
        - id: payment_routh      #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
          #uri: http://localhost:8001     #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**      #断言，路径相匹配的进行路由,为ture,可以经行端口适配。

        - id: payment_routh2     #payment_routh   #路由的ID，没有固定规则但要求唯一，简易配合服务名
          #uri: http://localhost:8001      #匹配后提供服务的路由地址,静态，写死了地址，只能调用一个服务
          uri: lb://cloud-payment-service #动态，lb://表示基于服务注册的负载均衡。
          predicates:
            - Path=/payment/lb/**       #断言，路径相匹配的进行路由
            #- After=2020-10-12T15:26:35.499+08:00[Asia/Shanghai]
            #- Cookie=username,jinunn
           # - Header=X-Request-Id,\d+  #请求头要有Header=X-Request-Id属性并且值为整数的正则表达式。

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #      defaultZone: http://eureka7002.com:7002/eureka/
      #      单机版eureka
      defaultZone: http://eureka7001.com:7001/eureka/